---
title: Bibliometric network analysis of Viking Age research (BibVik)
repo-actions: false
toc: false
format-links: false
---

BibVik is a project concerned with identifying trends in the published archaeological literature corresponding with shifting attitudes concerning the origins of the Viking Age.
Specifically, we address how research on various topics relating to the origins of the Viking Age manifests in the published record, including associations between various topics, methods and sources of evidence; how these modes of inquiry are related to researchers' personal or professional identities and relationships; and how citations are used to situate one's research in relation to prior work.

We implement critical approach to bibliometric research methods.
We recognize that open scholarly metadata, which is a bedrock of most modern bibliometric research, has intrinsic limitations that make it unsuitable for our analysis, and so we are experimenting with strategies for generating original data tailored for our research questions.
In this sense, BibVik is also a response to the limitations of bibliometric research, and presents a vision for doing more meaningful, critical, and explicitly feminist work in this domain.

This website hosts our preliminary research protocol, manuscript preprints, and other relevant materials.
All content is hosted and tracked at [github.com/zackbatist/BibVik](https://github.com/zackbatist/BibVik).

<!-- **Manuscript:**
Preprint of our manuscript (in progress)

**Workshop:**
Information for the workshop we hosted for the research community

**Scratchpad:**
Home for our ongoing analysis

**Codebook:**
A list of codes used to characterize scholarly works

**Research Protocol:**
Outlines the project's initial overall vision -->

