---
title: Citational Politics and Practices in Viking Age Archaeology and Beyond
title-block-style: plain
number-sections: false
toc-depth: 2
---

**Monday April 13 -- Tuesday April 14, 2026**\
**University of Oslo**

[Poster PDF](BibVik-workshop-poster.pdf) | [Poster HTML](BibVik-workshop-poster.html)

BibVik is a bibliometric study that aims to discover different threads and tendencies regarding how Viking Age archaeological research are pursued.
It takes a critical, feminist and reflexive stance on research practice and on how research practice can be documented and analyzed.

We are not alone in this approach.
Although archaeologists and others in the domain of Nordic cultural heritage are increasingly engaged in research on research practice, the work sometimes feel scattered or tangential to archaeologists' primary research interests.
This workshop therefore assemble a community of like-minded scholars who have not only done comprehensive and digitally-mediated archaeological meta-research rooted in bibliometric methods, but who have done so from a critical and feminist perspective.

The purpose of the workshop is twofold:

1. To exchange experience about the possibilities and challenges of conducting quantitative bibliometric studies.
2. To reflect on broader tendencies and challenges in referencing practices within archaeology, and on Viking Age archaeology specifically.

## Guiding Questions
Each presentation slot is 25 minutes, which includes time for questions directed to the speakers.
Time is also reserved for breaking out into focused group discussions and for structured plenary discussion at the end of each day.

**Discussion may focus on the following themes:**

- How can bibliometric, meta-research, and digital approaches in general be leveraged to produce or assist with feminist, anti-colonial, or other forms of reflexive critique within archaeology?
- What methodological challenges (including those relating to data availability and quality) exist, and how might we overcome them?
- What are the limits of bibliometric approaches, what voices do they exclude, and how might we better account for missing or under-represented perspectives?
- What specific considerations should be made when applying these approaches in the context of Viking Age archaeology and in other distinct subdisciplines, domains or areas of interest?
- How do we establish supportive referential practices in archaeological research, and avoid closed networks, and how may bibliometric studies contribute to this process?

Participants are welcome to access and contribute to a [shared notes file](https://docs.google.com/document/d/1uZNQ1aaLM-koc0nV854NksJi6naU-dZcs1zg1SoixC8/edit?usp=sharing).

## Program
### Monday, April 13
[Blindernveien 11, seminarrom 2](https://link.mazemap.com/vXsYMUcv)

| Start | End | Activity | Speaker |
| - | - | ----------- | --- |
| 12:00 | 12:15 | Introducing the BibVik Workshop | Julie Lund |
| 12:15 | 12:30 | Preliminary Findings from the BibVik Project | Isak Roalkvam |
| 12:30 | 13:30 | Lunch | |
| 13:30 | 13:55 | **References as paradata: what citations and references tell us about archaeological research practice** | Isto Huvila |
| 13:55 | 14:20 | **An anecdote and some reflections on citation practices in the age of the publication indicator** | Unn Pederson |
| 14:20 | 15:05 | Group Work | |
| 15:05 | 15:35 | Coffee | |
| 15:35 | 16:00 | **A Protocol for Analyzing Citational Practice in Viking Age Archaeology** | Zachary Batist |
| 16:00 | 16:45 | Plenum / Discussion | |
| 17:30 | | Drinks + Dinner | |

### Tuesday, April 14
[OASEN, Georg Sverdrups Hus](https://link.mazemap.com/O8lfLNtN)

| Start | End | Activity | Speaker |
| - | - | ----------- | --- |
| 09:00 | 10:00 | Organizing Meeting | |
| 10:00 | 10:25 | Coffee | |
| 10:25 | 10:50 | **Mapping collaborative networks in archaeological research software engineering** | Joe Roe |
| 10:50 | 11:15 | **Encouraging critical reflection in editorial work processes** | Mari Østmo |
| 11:15 | 12:00 | Group Work | |
| 12:00 | 13:00 | Lunch | |
| 13:00 | 13:25 | **A Scandinavian Viking Age?** | Espen Dalbakk |
| 13:25 | 13:50 | **Are we there yet? Assessing the Development in Open Access Publishing in Norwegian Archaeology** | Steinar Solheim |
| 13:50 | 14:30 | Group Work | |
| 14:30 | 15:00 | Coffee | |
| 15:00 | 16:30 | Plenum / Discussion | |


## Invited Talks

<!-- ### Introducing the BibVik Workshop
**Julie Lund**, University of Oslo

### Preliminary Findings from the BibVik Project
**Isak Roalkvam**, Aarhus University -->

#### References as paradata: what citations and references tell us about archaeological research practice
**Isto Huvila**, University of Uppsala

#### An anecdote and some reflections on citation practices in the age of the publication indicator
**Unn Pederson**, University of Oslo

<!-- ### Title TBD
**Zachary Batist**, McGill University -->

#### Mapping collaborative networks in archaeological research software engineering
**Joe Roe**, University of Copenhagen

#### Encouraging critical reflection in editorial work processes
**Mari Østmo**, University of Oslo

#### A Scandinavian Viking Age?
**Espen Dalbakk**, University of Oslo

#### Are we there yet? Assessing the Development in Open Access Publishing in Norwegian Archaeology
**Steinar Solheim**, University of Oslo


