---
title: Title TBD
# subtitle: xxx
date: today
authors:
  - name: Julie Lund 
    id: jl
    email: julie.lund@iakh.uio.no
    url: https://www.hf.uio.no/iakh/english/people/aca/archaeology/tenured/julielun/
    corresponding: true
    affiliations:
      - name: University of Oslo
        department: Archaeology, Conservation and History
        city: Oslo
        country: Norway
  - name: Isak Roalkvam
    id: ir
    email: isak.roalkvam@cas.au.dk
    url: https://www.au.dk/isak.roalkvam@cas.au.dk/
    orcid: 0000-0001-6974-1374
    affiliations:
      - name: University of Aarhus
        department: Archeology and Heritage Studies
        city: Aarhus
        country: Denmark
  - name: Zachary Batist
    id: zb
    email: zachary.batist@mcgill.ca
    url: https://zackbatist.info
    orcid: 0000-0003-0435-508X
    affiliations:
      - name: McGill University
        department: Epidemiology, Biostatistics and Occupational Health
        city: Montreal
        region: Québec
        country: Canada
abstract: |
  XXXX
keywords:
  - aaa
  - bbb
  - ccc
# funding: xxxx
# citation:
#   title: xxx
#   container-title: xxx
#   volume: xxx
#   doi: xxx
#   url: https://zackbatist.info/BibVik
filters: 
  - ../assets/count-para.lua
format:
  html: default
  # pdf:
  #   documentclass: article
  #   geometry:
  #     - top = 1in
  #     - bottom = 1in
  #     - left = 1in
  #     - right = 1in
  #   colorlinks: true
  #   toc: false
  #   include-in-header:
  #     text: |
  #       \usepackage{orcidlink}
  #       \usepackage{marvosym}
  #   template-partials:
  #     - ../assets/title.tex
---

<!-- ```{r setup}

```

```{r dependencies}

```

```{r plot-theme}

``` -->


{{< include sections/01_introduction.qmd >}}
{{< include sections/02_background.qmd >}}
{{< include sections/03_methods-materials.qmd >}}
{{< include sections/04_findings.qmd >}}
{{< include sections/05_discussion.qmd >}}
{{< include sections/06_conclusion.qmd >}}
{{< include sections/11_references.qmd >}}
{{< include sections/12_back-matter.qmd >}}
{{< include sections/13_supplement.qmd >}}
