"""
bibvik.corrections — Manual curation corrections for bibliography.json.

Two files:

    corrections.yaml      — confirmed corrections, applied by --postprocess
    corrections_draft.yaml — candidate corrections generated by the pipeline,
                             reviewed by the researcher before promotion

corrections.yaml actions:

    - action: merge
      keep: citekey_a
      discard: citekey_b
      note: "reason"

    - action: delete
      citekey: citekey_a
      note: "reason"

    - action: set
      citekey: citekey_a
      field: author
      value: [{family: Sindbæk, given: Søren Michael}]
      note: "reason"

corrections_draft.yaml has the same format plus:

    _source: "near_duplicate | cross_script | noauthor_recovery | ocr_candidate"
    _confidence: 0.0–1.0   (pipeline's confidence this correction is right)

Workflow:
    1. Pipeline writes candidates to corrections_draft.yaml during --postprocess
    2. Researcher reviews corrections_draft.yaml
    3. Accepted entries are moved to corrections.yaml
    4. Next --postprocess run applies corrections.yaml

Usage:
    Applied automatically by postprocess.run_postprocess().
    Draft writing is triggered by the same run.
    To apply standalone:
        python -m bibvik.corrections --bib output/bibliography.json
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

CORRECTIONS_FILENAME       = "corrections.yaml"
CORRECTIONS_DRAFT_FILENAME = "corrections_draft.yaml"


# ── YAML loading ──────────────────────────────────────────────────────────────

def _load_yaml(path: Path) -> list[dict]:
    """Load a YAML file as a list. Returns [] if absent or empty."""
    if not path.exists():
        return []
    try:
        import yaml
    except ImportError:
        logger.warning(
            "PyYAML not installed; cannot load %s. pip install pyyaml", path
        )
        return []
    with path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not data:
        return []
    if not isinstance(data, list):
        logger.error("%s must be a YAML list; got %s", path, type(data).__name__)
        return []
    return data


def _save_yaml(path: Path, data: list[dict]) -> None:
    """Write a list of dicts to a YAML file."""
    try:
        import yaml
    except ImportError:
        logger.warning("PyYAML not installed; cannot write %s", path)
        return
    with path.open("w", encoding="utf-8") as f:
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False,
                  sort_keys=False)


# ── Apply corrections ─────────────────────────────────────────────────────────

def apply_corrections(bib: dict, corrections: list[dict]) -> dict:
    """
    Apply confirmed corrections to the bibliography in place.
    Returns counts: {merge, delete, set, skipped}.
    """
    counts = {"merge": 0, "delete": 0, "set": 0, "skipped": 0}

    for i, corr in enumerate(corrections):
        action = corr.get("action", "").lower()

        if action == "merge":
            keep    = corr.get("keep", "")
            discard = corr.get("discard", "")
            note    = corr.get("note", "")

            if not keep or not discard:
                logger.warning("Correction %d (merge): missing keep or discard", i)
                counts["skipped"] += 1
                continue
            if keep not in bib:
                logger.warning("Correction %d (merge): keep citekey %r not found", i, keep)
                counts["skipped"] += 1
                continue
            if discard not in bib:
                logger.debug("Correction %d (merge): discard %r already absent", i, discard)
                continue

            for cb in bib[discard].get("cited_by", []):
                if cb not in bib[keep].get("cited_by", []):
                    bib[keep].setdefault("cited_by", []).append(cb)

            bib[discard]["_deleted"]     = True
            bib[discard]["_merged_into"] = keep
            if note:
                bib[discard]["_correction_note"] = note

            logger.info("Merged %r into %r", discard, keep)
            counts["merge"] += 1

        elif action == "delete":
            citekey = corr.get("citekey", "")
            note    = corr.get("note", corr.get("reason", ""))

            if not citekey:
                logger.warning("Correction %d (delete): missing citekey", i)
                counts["skipped"] += 1
                continue
            if citekey not in bib:
                logger.debug("Correction %d (delete): %r already absent", i, citekey)
                continue

            bib[citekey]["_deleted"] = True
            if note:
                bib[citekey]["_correction_note"] = note

            logger.info("Deleted %r", citekey)
            counts["delete"] += 1

        elif action == "set":
            citekey = corr.get("citekey", "")
            field   = corr.get("field", "")
            value   = corr.get("value")
            note    = corr.get("note", "")

            if not citekey or not field:
                logger.warning("Correction %d (set): missing citekey or field", i)
                counts["skipped"] += 1
                continue
            if citekey not in bib:
                logger.warning("Correction %d (set): citekey %r not found", i, citekey)
                counts["skipped"] += 1
                continue
            if value is None:
                logger.warning("Correction %d (set): missing value", i)
                counts["skipped"] += 1
                continue

            bib[citekey][field] = value
            bib[citekey].setdefault("_corrections_applied", []).append(field)
            if note:
                bib[citekey]["_correction_note"] = note

            logger.info("Set %r.%s", citekey, field)
            counts["set"] += 1

        else:
            logger.warning("Correction %d: unknown action %r", i, action)
            counts["skipped"] += 1

    return counts


# ── Draft generation ──────────────────────────────────────────────────────────

def write_draft_corrections(
    bib: dict,
    output_dir: Path,
    existing_corrections: list[dict] | None = None,
) -> int:
    """
    Scan the bibliography for pipeline-flagged issues and write candidate
    corrections to corrections_draft.yaml.

    Sources:
        _near_duplicate_candidate  — near-duplicate pairs, LLM inconclusive
        _cross_script_duplicate_candidate — cross-script pairs, title overlap insufficient
        _author_recovery_failed    — NOAUTHOR entries where LLM couldn't extract author
        _ocr_candidate             — papers flagged as alternate OCR candidates

    Skips any candidate where an equivalent correction already exists in
    corrections.yaml (same citekeys, same action).

    Returns number of draft entries written.
    """
    existing_corrections = existing_corrections or []
    existing_pairs = {
        (c.get("keep"), c.get("discard"))
        for c in existing_corrections
        if c.get("action") == "merge"
    }
    existing_deletions = {
        c.get("citekey")
        for c in existing_corrections
        if c.get("action") == "delete"
    }

    drafts = []
    seen_pairs: set[frozenset] = set()

    for ck, entry in bib.items():
        if entry.get("_deleted"):
            continue

        # Near-duplicate candidates
        for partner in entry.get("_near_duplicate_candidate", []):
            pair = frozenset([ck, partner])
            if pair in seen_pairs:
                continue
            seen_pairs.add(pair)
            if (ck, partner) in existing_pairs or (partner, ck) in existing_pairs:
                continue
            partner_entry = bib.get(partner, {})
            drafts.append({
                "action":      "merge",
                "keep":        ck,
                "discard":     partner,
                "note":        "",
                "_source":     "near_duplicate",
                "_confidence": entry.get("_near_duplicate_score", 0.0),
                "_keep_title":    entry.get("title", ""),
                "_discard_title": partner_entry.get("title", ""),
            })

        # Cross-script duplicate candidates
        for partner in entry.get("_cross_script_duplicate_candidate", []):
            pair = frozenset([ck, partner])
            if pair in seen_pairs:
                continue
            seen_pairs.add(pair)
            if (ck, partner) in existing_pairs or (partner, ck) in existing_pairs:
                continue
            partner_entry = bib.get(partner, {})
            drafts.append({
                "action":      "merge",
                "keep":        ck,
                "discard":     partner,
                "note":        "",
                "_source":     "cross_script",
                "_confidence": 0.5,
                "_keep_title":    entry.get("title", ""),
                "_discard_title": partner_entry.get("title", ""),
            })

        # Failed NOAUTHOR author recovery
        if entry.get("_author_recovery_failed") and ck not in existing_deletions:
            drafts.append({
                "action":      "set",
                "citekey":     ck,
                "field":       "author",
                "value":       [],
                "note":        "",
                "_source":     "noauthor_recovery",
                "_confidence": 0.0,
                "_raw_citation": entry.get("_raw_citation", ""),
                "_title":        entry.get("title", ""),
            })

        # OCR candidates — flagged by alternate OCR fallback as still unresolved
        if entry.get("_ocr_candidate") and ck not in existing_deletions:
            drafts.append({
                "action":      "delete",
                "citekey":     ck,
                "note":        "",
                "_source":     "ocr_candidate",
                "_confidence": 0.3,
                "_raw_citation": entry.get("_raw_citation", ""),
                "_title":        entry.get("title", ""),
            })

    draft_path = output_dir / CORRECTIONS_DRAFT_FILENAME
    if drafts:
        _save_yaml(draft_path, drafts)
        logger.info("Wrote %d draft corrections to %s", len(drafts), draft_path)
    elif draft_path.exists():
        logger.info("No new draft corrections; %s unchanged", draft_path)

    return len(drafts)


# ── Main entry point ──────────────────────────────────────────────────────────

def run_corrections(bib_path: Path, corrections_path: Path | None = None) -> dict:
    """
    Load bibliography.json, apply corrections.yaml, write back.
    Returns counts.
    """
    bib_path         = Path(bib_path)
    corrections_path = corrections_path or (bib_path.parent / CORRECTIONS_FILENAME)

    bib         = json.loads(bib_path.read_text(encoding="utf-8"))
    corrections = _load_yaml(Path(corrections_path))

    if not corrections:
        return {"merge": 0, "delete": 0, "set": 0, "skipped": 0}

    counts = apply_corrections(bib, corrections)
    bib_path.write_text(json.dumps(bib, ensure_ascii=False, indent=2), encoding="utf-8")
    return counts


if __name__ == "__main__":
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser()
    parser.add_argument("--bib",         default="output/bibliography.json")
    parser.add_argument("--corrections", default=None)
    args = parser.parse_args()
    counts = run_corrections(
        Path(args.bib),
        Path(args.corrections) if args.corrections else None,
    )
    print(f"merge={counts['merge']}  delete={counts['delete']}  "
          f"set={counts['set']}  skipped={counts['skipped']}")
