Meeting Notes\
Zack, Julie and Isak\
Monday June 16, 15:15 CEST / 9:15 EST

# Discussion Topics

## Developing the codebook
Julie worked on it with another colleague (I don't recall his name).
We discussed means of improving it further.
Specifically: develop groupings, and highlighting or boldening terms that stand out as the core concept or heading.

We also clarified how this is an iterative process.
The codes are not meant to be prescriptive, and should adapt to reflect the contents of the corpus and the realizations we make as coding progresses.

## Assessing the quality of scholarly metadata
Zack looked into the quality of scholarly metadata indexes, and found that they are not really suited for non-anglophone monographs and grey literature, which constitutes a significant aspect of our corpus.
He proposed an alternative solution: to use [Grobid](https://grobid.readthedocs.io/) to extract bibliographic references from PDFs using targeted machine learning algorithms.

This approach has a few caveats: We need full and clean PDFs of all works in the corpus, which may be particularly challenging for books. Julie has this covered based on her extensive library and teaching materials.
For works that are published as part of anthologies and edited volumes, we also need to isolate references for each chapter or book section.
Zack will develop a workflow to assist with this vetting, and Isak will test it out.

This led to some discussion about the nature and scope of the corpus.
We reiterated the sense that we should be led by the questions and the practical analytical challenges, rather than the data contained in the seed paper.
For instance, the disproportionate number of references in a book relative to a journal article may affect the constitution of a network and generate misleading findings (especially regarding centrality metrics), and it may be prudent to exclude them, or to replace them with a series of papers by the same author that cover the same ground as the book.
Moreover, an excavation report may be more descriptive and engage with the literature to a lesser extent than an "standalone" study (for lack of a better term right now), and we may want to discard those.
These considerations make the difference between an "easy" bibliometric analysis and a meaningful one.

## Miscellaneous
Zack mentioned his brief [social media interactions](https://archaeo.social/@zackbatist/114671854891720061), which pointed to Christian Bergeron's recent work with the same/similar toolsets, and whose [presentation](https://pad.gwdg.de/s/LjbjSAMyj) in April coincidentally helped inspire those whole project.
Zack is also consulting with Till Grallert, who develops software to convert between TEI and bibtex (among other data formats used to store bibliographic data).
It's great that we're relying so much on tools developed by the digital humanities!

We addressed the general plans for the workshop, which we agreed we should hold in March.
This will provide greater opportunity to generate meaningful findings and to invite other interesting participants.

# Action Items
**Next meeting:**
Monday June 30, 15:15 CEST / 9:15 EST

**Zack:**

- Developing a workflow for vetting the quality of the base data (by Friday June 20)
- Verifying the results of Grobid

**Isak:**

- Testing the vetting workflow

**Julie:**

- Revising the codebook
- Grouping topics, bolding the major part, and describing scope notes

# Links and references
<https://grobid.readthedocs.io>\
<https://www.youtube.com/watch?v=bgpsRrSeyIw>\
<https://pad.gwdg.de/s/LjbjSAMyj>\
<https://github.com/OpenArabicPE/convert_tei-to-bibliographic-data>

