Meeting Notes\
Zack, Julie and Isak\
Friday May 16, 15:15 CEST / 9:15 EST

# Discussion
## Developing a controlled vocabulary
- Three axes:
	- Topics: What is the paper about? (i.e. diaspora, mobility, gender, ritual, etc)
	- Methods: What methods were applied in the paper? (i.e. spatial analysis, genetics, stable isotope analysis, finds analysis)
	- Kind of contribution (i.e. field report, "standard" scientific paper, review of prior work, opinion)
- The medium (i.e. journal article, book, chapter in an edited volume, etc) will be identified by CrossRef and does not need to be annotated.
- It's ok to assign multiple terms to each record.

## Coding process
- A research assistant will be able to start work in September, and will be able to work for four weeks.
- Limited to review of titles and abstracts, or if there is no abstract, the introductions and conclusions.
- Since this does not involve comprehensive or open coding, we can just do this in a spreadsheet rather than some specialized QDA software.
- The research assistant will ideally be a more experienced student in the field of Viking Age archaeology.
- Zack will schedule weekly check-ins with the research assistant and make himself available to address any methodological questions or concerns.

## Analysis of references
- We won't be able to qualitatively annotate references due to lack of time relative to the corpus' volume.
- NLP using scite is not as useful as initially thought.
	- tends to "play it safe" by coding references as neutral mentions when human coders identify a more robust stance (see Bakker et al. 2023).
	- Its corpus is limited to works put out by partnered publishers.
- Potential alternative to scite, but requires greater knowledge of NLP to implement:
	- https://github.com/davidjurgens/citation-function
	- https://jurgens.people.si.umich.edu/citation-function
- We may be able to derive a sample based on network statistics, i.e. the most or least central references.

## Analysis of gender
- Our intent is to identify citation biases against women.
- The goal is not to identify gender diversity, which is not supported by our method.

## Predictions and expectations
- We're gonna find sub-clusters within clusters, and bridging clusters.
- Some sub-clusters will be tight-knit and closed, others very broad and open.
- Some will be very focused on specific topics.
- There will be many links across institutions, they are not really that fixed.
- Some citation chains will emerge that reflect casual observations (just a few examples):
	- Lots of cross-references within the Mälaren valley community.
	- Tight-knit cluster among papers that are concerned with ritual.
	- Major computational cluster at Aarhus.
- If had a broader time horizon, we might be able to trace "genealogies of affiliation" by tracing how identities change based on the evolution of their collaborative networks.
- Clustering in methods by "academic upbringing", which has a localized character
- We may be able to find associations based on age, but mainly by doing a rough assessment of the n most and least central nodes, rather than keying age into the data.

## Additional ideas and insights
- Keeping track of topics independently from citational links enables us to validate whether topics are actually clustered around certain individuals or papers, or whether there are diverse centres.
- We'll be able to do some non-network descriptive statistics:
	- Distribution of topics by affiliations of authors.
	- Distribution of topics by number of co-authors.
	- Temporal distributions of genders of lead authors.
	- Gender of lead author by size and genders of their co-authors.

## Logistics
- Keep things on GitHub for now.
- Keep our eyes open for alternative collaborative writing platforms that may emerge over the next few months (including via the [archaeo-social](https://about.archaeo.social/) collective).

# Action items
**Next meeting:**
Monday June 2, 15:15 CEST / 9:15 EST

**Zack:**

- Assemble a series of core variables to be included in a data frame
- Initiate a script to scrape abstracts and metadata
- Modify the research protocol with today's notes
	- Expectations and predictions
	- Tone down expectations for analysis of references (based on volume of papers, limited time)
	- Document the controlled vocabulary and coding process

**Julie:**

- Draft controlled vocabulary for article annotation

**Isak:**

- Review and modify the R script

# Links and references
- Peterson, David, and Aaron Panofsky. 2023. “Metascience as a Scientific Social Movement.” Minerva 61 (2): 147–74. https://doi.org/10.1007/s11024-023-09490-3.
- Bakker, Caitlin, Nicole Theis-Mahon, and Sarah Jane Brown. 2023. “Evaluating the Accuracy of Scite, a Smart Citation Index.” Hypothesis: Research Journal for Health Information Professionals 35 (2). https://doi.org/10.18060/26528.
- Thesis by Julie's former student, about us/we/them in Viking Age literature.
- Open source alternative to scite:
	- https://github.com/davidjurgens/citation-function
	- https://jurgens.people.si.umich.edu/citation-function


